[connections.snowflake]
account = "LARAJJK-AHB36729"
user = "CraigRobertson"
private_key_file = "rsa_key.p8"
private_key_file_pwd = "SnowFlake"
role = "SYSADMIN"
warehouse = "COMPUTE_W"
database = "SMOOTHIES"
schema = "PUBLIC"
